/* date = October 12th 2024 4:18 pm */

#if !defined(GLProc)
#define GLProc(name, type)
#endif

GLProc(glFramebufferRenderbuffer, FRAMEBUFFERRENDERBUFFER)
GLProc(glGenRenderbuffers, GENRENDERBUFFERS)
GLProc(glDeleteRenderbuffers, DELETERENDERBUFFERS)
GLProc(glBindRenderbuffer, BINDRENDERBUFFER)
GLProc(glRenderbufferStorage, RENDERBUFFERSTORAGE)
GLProc(glFramebufferTexture2D, FRAMEBUFFERTEXTURE2D)
GLProc(glGenFramebuffers, GENFRAMEBUFFERS)
GLProc(glDeleteFramebuffers, DELETEFRAMEBUFFERS)
GLProc(glBindFramebuffer, BINDFRAMEBUFFER)
GLProc(glCheckFramebufferStatus, CHECKFRAMEBUFFERSTATUS)
GLProc(glGenBuffers, GENBUFFERS)
GLProc(glDeleteBuffers, DELETEBUFFERS)
GLProc(glBindBuffer, BINDBUFFER)
GLProc(glGenerateMipmap, GENERATEMIPMAP)
GLProc(glCreateShader, CREATESHADER)
GLProc(glShaderSource, SHADERSOURCE)
GLProc(glCompileShader, COMPILESHADER)
GLProc(glGetShaderiv, GETSHADERIV)
GLProc(glGetShaderInfoLog, GETSHADERINFOLOG)
GLProc(glDeleteShader, DELETESHADER)
GLProc(glCreateProgram, CREATEPROGRAM)
GLProc(glAttachShader, ATTACHSHADER)
GLProc(glLinkProgram, LINKPROGRAM)
GLProc(glGetProgramiv, GETPROGRAMIV)
GLProc(glDetachShader, DETACHSHADER)
GLProc(glGetProgramInfoLog, GETPROGRAMINFOLOG)
GLProc(glDeleteProgram, DELETEPROGRAM)
GLProc(glUseProgram, USEPROGRAM)
GLProc(glGenVertexArrays, GENVERTEXARRAYS)
GLProc(glDeleteVertexArrays, DELETEVERTEXARRAYS)
GLProc(glBindVertexArray, BINDVERTEXARRAY)
GLProc(glBufferData, BUFFERDATA)
GLProc(glEnableVertexAttribArray, ENABLEVERTEXATTRIBARRAY)
GLProc(glVertexAttribPointer, VERTEXATTRIBPOINTER)
GLProc(glUniformMatrix4fv, UNIFORMMATRIX4FV)
GLProc(glUniform2f, UNIFORM2F)
GLProc(glUniform4f, UNIFORM4F)
GLProc(glGetUniformLocation, GETUNIFORMLOCATION)
GLProc(glBufferSubData, BUFFERSUBDATA)
GLProc(glUniform4fv, UNIFORM4FV)
GLProc(glUniform1i, UNIFORM1I)
GLProc(glUniform1f, UNIFORM1F)
GLProc(glUniform2iv, UNIFORM2IV)
GLProc(glUniform2fv, UNIFORM2FV)
GLProc(glDrawElementsBaseVertex, DRAWELEMENTSBASEVERTEX)
GLProc(glRenderbufferStorageMultisample, RENDERBUFFERSTORAGEMULTISAMPLE)
GLProc(glTexImage2DMultisample, TEXIMAGE2DMULTISAMPLE)
GLProc(glVertexAttribDivisor, VERTEXATTRIBDIVISOR)
GLProc(glDrawElementsInstanced, DRAWELEMENTSINSTANCED)

#if OS_WINDOWS
GLProc(glActiveTexture, ACTIVETEXTURE)
#endif

#undef GLProc
